Dev Search/Home/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('project/', include('project.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="user/reset_password.html"),name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='user/reset_password_sent.html'),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/reset.html'),name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="user/reset_password_complete.html"),name="password_reset_complete"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"

Dev Search/api/urls.py
from django.urls import path , include
from . import views

app_name = 'api'

from rest_framework_simplejwt.views import (
    TokenObtainPairView, #generate json web token
    TokenRefreshView,#generate refresh web token
)

urlpatterns = [
    path('user/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('user/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('project/', views.getProjects),
    path('project/<str:pk>/', views.getProject),
    path('project/<str:pk>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag),
]

Dev Search/project/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'project'

urlpatterns = [
    path('', views.index , name="Home"),
    path('createproject/', views.createProject , name="Create"),
    path('updateproject/<str:pk>/', views.updateProject , name="Update"),
    path('deleteproject/<str:pk>/', views.deleteProject , name="Delete"),
    path('<str:pk>/', views.about , name="About"),
]

Dev Search/user/urls.py
from django.urls import path , include
from . import views 

app_name = 'user'

urlpatterns = [
    path('', views.index , name="Home"),
    path('login/', views.loginUser , name="login"),
    path('logout/', views.logoutUser , name="logout"),
    path('register/', views.registerUser , name="register"),
    path('account/', views.userAccount , name="account"),
    path('editProfile/', views.editProfile , name="edit-profile"),
    path('createSkill/', views.createSkill , name="create-skill"),
    path('inbox/', views.inbox , name="inbox"),
    path('viewMessage/<str:pk>/', views.viewMessage , name="viewMessage"),
    path('createMessage/<str:pk>/', views.createMessage , name="createMessage"),
    path('deleteSkill/<str:pk>/', views.deleteSkill , name="delete-skill"),
    path('updateSkill/<str:pk>/', views.updateSkill , name="update-skill"),
    path('profile/<str:pk>/', views.profile , name="Profile"),
]

Dev Search/project/models.py
# one
from django.db import models
from django.utils import timezone
from user.models import Profile
import uuid

class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True) 
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    featured_image = models.ImageField(upload_to='project', null=True, blank=True,default='project_default/default.jpg')
    source_code = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag',blank=True)
    vote_count = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(default=timezone.now)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['-vote_ratio','-vote_count','title']

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_count = totalVotes
        self.vote_ratio = ratio
        self.save()

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id',flat=True)
        return queryset

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ''
        return url

class Review(models.Model):
    VOTE_TYPE = ( 
        ('up','Up Vote'),
        ('down','Down Vote'),
    )
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(blank=True, null=True)
    value = models.CharField(max_length=200,choices=VOTE_TYPE)
    created = models.DateTimeField(default=timezone.now)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner','project']]

    def __str__(self) -> str:
        return f"{self.value}  {self.owner}"

    pass 

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(default=timezone.now)
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)

    def __str__(self) -> str:
        return self.name 

    pass 

Dev Search/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone 
import uuid 

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=20, null=True, blank=True)
    location = models.CharField(max_length=20, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(upload_to='user', null=True, blank=True,default='user_default/mehdi.png')
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_stackoverflow = models.CharField(max_length=200, null=True, blank=True)
    social_linkedIn = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)
    social_instagram = models.CharField(max_length=200, null=True, blank=True)

    created = models.DateTimeField(default=timezone.now)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return str(self.username)
    
    class Meta:
        ordering = ['created']

    @property
    def profileURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url

    pass

class Skill(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True, blank=True)
    desc = models.TextField(null=True, blank=True)

    created = models.DateTimeField(default=timezone.now)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return str(self.name)
    pass 


class Message(models.Model):
    sender = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    recipient = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True,related_name="messages")
    name = models.CharField(max_length=200,null=True,blank=True)
    email = models.EmailField(max_length=200,null=True,blank=True)
    subject = models.CharField(max_length=200,null=True,blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False,null=True)

    created = models.DateTimeField(default=timezone.now)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.subject

    class Meta:
        ordering = ['is_read','-created']

Dev Search/user/views.py
import re
import django
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from project.models import Project, Tag
from .models import Profile, Skill, Message
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from .forms import CustomUserCreationForm, CustomProfileForm, skillForm, MessageForm
from django.contrib import messages
from django.db.models import Q
from .utils import searchProjects, paginateProfiles
from django.contrib.auth.decorators import login_required
# Create your views here.


def loginUser(request):
    if request.user.is_authenticated:
        return redirect('user:Profile')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User name does not exit")
            return redirect('user:login')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.info(request, "Login Successfully")
            return redirect(request.GET['next'] if 'next' in request.GET else 'user:account')
        else:
            messages.error(request, "User or Password does not match")
            return redirect('user:login')

    return render(request, 'user/login_register.html')


def logoutUser(request):
    logout(request)
    messages.info(request, "Logout Successfully")
    return redirect('user:Home')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            # messages.success(request,'Register successfully')
            login(request, user)
            return redirect('user:edit-profile')  # redirect to profile
        else:
            messages.error(request, 'Some Error Occured During Registeration')

    content = {'page': page, 'form': form}
    return render(request, 'user/login_register.html', content)


def index(request):
    profiles, search_query = searchProjects(request)
    paginator, custom_range, profiles = paginateProfiles(request, profiles, 12)

    content = {'profiles': profiles, 'search_query': search_query,
               'paginator': paginator, 'custom_range': custom_range}
    return render(request, 'user/index.html', content)


def profile(request, pk):
    profile = Profile.objects.get(id=pk)

    majorSkill = profile.skill_set.exclude(desc="")
    minorSkill = profile.skill_set.filter(desc="")

    projects = profile.project_set.all()
    paginator, custom_range, projects = paginateProfiles(request, projects, 4)

    content = {'profile': profile, 'paginator': paginator, 'custom_range': custom_range,
               'majorSkill': majorSkill, 'minorSkill': minorSkill,'projects':projects}
    return render(request, 'user/profile.html', content) 


@login_required(login_url='login')
def userAccount(request):
    profile = request.user.profile

    skills = profile.skill_set.all()
    projects = profile.project_set.all()

    paginator1, custom_range1, skills = paginateProfiles(
        request, skills, 4)  # setting up for skill
    paginator, custom_range, projects = paginateProfiles(
        request, projects, 4)  # setting up for project

    content = {'profile': profile, 'skills': skills, 'projects': projects, 'paginator': paginator,
               'custom_range': custom_range, 'paginator1': paginator1, 'custom_range1': custom_range1}
    return render(request, 'user/account.html', content)


@login_required(login_url='login')
def editProfile(request):
    profile = request.user.profile
    form = CustomProfileForm(instance=profile)

    if request.method == 'POST':
        form = CustomProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('user:account')

    content = {'form': form}
    return render(request, 'user/profile_form.html', content)


@login_required(login_url='login')
def createSkill(request):
    profile = request.user.profile
    form = skillForm()

    if request.method == 'POST':
        form = skillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request, "Skill was created !")
            return redirect('user:account')

    content = {'form': form}
    return render(request, 'user/skill_form.html', content)


@login_required(login_url='login')
def updateSkill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = skillForm(instance=skill)

    if request.method == 'POST':
        form = skillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, "Skill was updated !")
            return redirect('user:account')

    content = {'form': form}
    return render(request, 'user/skill_form.html', content)


@login_required(login_url='login')
def deleteSkill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)

    if request.method == 'POST':
        skill.delete()
        messages.info(request, "Skill have been removed !")
        return redirect('user:account')

    content = {'skill': skill}
    return render(request, 'user/skill_delete.html', content)


@login_required(login_url='login')
def inbox(request):
    profile = request.user.profile
    messageReq = profile.messages.all()
    unReadCount = messageReq.filter(is_read=False).count()
    content = {'message': messageReq, 'unReadCount': unReadCount}
    return render(request, 'user/inbox.html', content)


@login_required(login_url='login')
def viewMessage(request, pk):
    profile = request.user.profile
    messageReq = profile.messages.get(id=pk)
    if messageReq.is_read == False:
        messageReq.is_read = True
        messageReq.save()
    content = {'messageReq': messageReq}
    return render(request, 'user/message.html', content)

# @login_required(login_url='login')


def createMessage(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile
    except:
        sender = None

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()
            messages.success(request, "Your Message was successfull send !")
            return redirect('user:Profile', pk=recipient.id)

    content = {'recipient': recipient, 'form': form}
    return render(request, 'user/message-form.html', content)

Dev Search/templates/user/account.html
{% extends 'base-project.html' %}
{% load static %}
{% block title %}Account{% endblock title %}
{% block style %}
<style>
  .pagination {
    margin-top: 2rem;
    margin-bottom: 2rem;
  }
</style>
{% endblock style %}
{% block body %}



  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'user:edit-profile' %}"><i class="im im-edit"></i> Edit</a>
              {% if profile.profileURL == '' %}
              <img class="avatar avatar--md" style="height: 20rem;width: 20rem;" src="{% static 'media/user_default/mehdi.png' %}" alt="image" />
              {% else %}
              <img class="avatar avatar--md" style="height: 20rem;width: 20rem;" src="{{profile.profileURL}}" alt="image" />
              {% endif %}
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if profile.social_stackoverflow %}
                  <li>
                    <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_linkedIn %}
                  <li>
                    <a title="LinkedIn" href="{{profile.social_linkedIn}}" target="_blank"><i class="im im-linkedin"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_website %}
                  <li>
                    <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                  </li>
                {% endif %}

              </ul>
              {% if request.user.profile.id != profile.id %}
              <a href="{% url 'user:createMessage' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'user:create-skill' %}?next=/account"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">

            {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill}}</h4>
                <p>
                  {{skill.desc|slice:"150"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'user:update-skill' skill.id %}?next=/account"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'user:delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
            
          </table>

          {% include 'pagination.html' with querySet=skills custom_range=custom_range1 %}


          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'project:Create' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">

            {% for project in projects %}
            <tr>
              <td class="settings__thumbnail">
                {% if project.imageURL == '' %}
                <img class="project__thumbnail" src="{% static 'media/project_default/default.jpg' %}" alt="project thumbnail" />
                {% else %}
                <img class="project__thumbnail" src="{{project.imageURL}}" alt="project thumbnail" />
                {% endif %}
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'project:About' project.id %}">{{project.title}}</a>
                <p>
                  {{project.description|slice:"150"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'project:Update' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'project:Delete' project.id %}"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %} 

            
          </table>
          {% include 'pagination.html' with querySet=projects custom_range=custom_range %}
        </div>
      </div>
    </div>
  </main>


{% endblock body %}
{% block script %}
<script>

</script>
{% endblock script %}

Dev Search/templates/user/inbox.html
{% extends 'base-project.html' %}
{% block title %}Home{% endblock title %}
{% block style %}
<style>

</style>
{% endblock style %}
{% block body %}

  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unReadCount}}</span>)</h3>
      <ul class="messages">
        {% for mess in message %}
        {% if mess.is_read == False %}
        <li class="message message--unread">
        {% else %}
        <li class="message">  
        {% endif %}
        <a href="{% url 'user:viewMessage' mess.id %}">
            <span class="message__author">{{mess.name}}</span>
            <span class="message__subject">{{mess.subject}}</span>
            <span class="message__date">{{mess.created}}</span>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </main>

{% endblock body %}
{% block script %}
<script>

</script>
{% endblock script %}

Dev Search/templates/user/message-form.html
{% extends 'base-project.html' %}
{% block title %}Home{% endblock title %}
{% block style %}
<style>
  
</style>
{% endblock style %}
{% block body %}

    <!-- Main Section -->
    <main class="formPage my-xl">
      <div class="content-box">
          <div class="formWrapper">
              <a class="backButton" href="{% url 'user:Profile' recipient.id %}"><i class="im im-angle-left"></i></a>
              <br>

              <form class="form" action="" method="POST">
                {% csrf_token %}
                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                  <label for="formInput#text">{{form.name.label}}: </label>
                  {{form.name}}
                </div>
                <div class="form__field">
                  <label for="formInput#text">{{form.email.label}}: </label>
                  {{form.email}}
                </div>
                {% endif %}
                <div class="form__field">
                  <label for="formInput#text">{{form.subject.label}}: </label>
                  {{form.subject}}
                </div>
                <div class="form__field">
                  <label for="formInput#text">{{form.body.label}}: </label>
                  {{form.body}}
                </div>
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
              </form>
          </div>
      </div>
  </main>
{% endblock body %}
{% block script %}
<script>

</script>
{% endblock script %}

Dev Search/templates/user/message.html
{% extends 'base-project.html' %}
{% block title %}Home{% endblock title %}
{% block style %}
<style>

</style>
{% endblock style %}
{% block body %}
<!-- Main Section -->
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'user:inbox' %}"><i class="im im-angle-left"></i></a>
      <h2 class="message__subject">{{messageReq.subject}}</h4>
        {% if messageReq.sender %}
        <a href="{% url 'user:Profile' messageReq.sender.id %}" class="message__author">{{messageReq.name}}</a>
        {% else %}
        <p class="message__author">{{messageReq.name}} </p>
        {% endif %}
        <p class="message__date">{{messageReq.created}}</p>
        <div class="message__body">
          {{messageReq.body}}
        </div>
    </div>
  </div>

{% endblock body %}
{% block script %}
<script>

</script>
{% endblock script %}

Dev Search/templates/user/profile.html
{% extends 'base-project.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block style %}
<style>
  .pagination {
    width: 100%;
    margin-top: 2rem;
    margin-bottom: 2rem;
  }
</style>
{% endblock style %}
{% block body %}

    <!-- Main Section -->
    <main class="profile my-md">
      <div class="container">
        <div class="layout">
          <div class="column column--1of3">
            <div class="card text-center">
              <div class="card__body dev">
                {% if profile.profileURL == '' %}
                <img class="avatar avatar--md" style="height: 20rem;width: 20rem;" src="{% static 'media/user_default/mehdi.png' %}" alt="image" />
                {% else %}
                <img class="avatar avatar--md" style="height: 20rem;width: 20rem;" src="{{profile.profileURL}}" alt="image" />
                {% endif %}
                <h2 class="dev__name">{{profile.name}}</h2>
                <p class="dev__title">{{profile.short_intro}}</p>
                <p class="dev__location">{{profile.location}}</p>
                <ul class="dev__social">

                  {% if profile.social_github %}
                    <li>
                      <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                    </li>
                  {% endif %}
                  {% if profile.social_stackoverflow %}
                    <li>
                      <a title="Stackoverflow" href="{{profile.social_stackoverflow}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                    </li>
                  {% endif %}
                  {% if profile.social_linkedIn %}
                    <li>
                      <a title="LinkedIn" href="{{profile.social_linkedIn}}" target="_blank"><i class="im im-linkedin"></i></a>
                    </li>
                  {% endif %}
                  {% if profile.social_website %}
                    <li>
                      <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                    </li>
                  {% endif %}

                </ul>
                {% if request.user.profile.id != profile.id %}
                <a href="{% url 'user:createMessage' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="column column--2of3">
            <div class="devInfo">
              <h3 class="devInfo__title">About Me</h3>
              <p class="devInfo__about">
                {{profile.bio}}
              </p>
            </div>
            <div class="devInfo">
              <h3 class="devInfo__title">Skills</h3>
              <div class="devInfo__skills">
                
                {% if majorSkill %}
                  {% for skill in majorSkill %}
                  <div class="devSkill">
                    <h4 class="devSkill__title">{{skill}}</h4>
                    <p class="devSkill__info">
                      {{skill.desc|slice:":150"}}
                    </p>
                  </div>
                  {% endfor %}
                {% else %}
                  No skill yet but 
                {% endif %}
  

                {% if minorSkill %}
                <h3 class="devInfo__subtitle">Other Skills</h3>
                <div class="devInfo__otherSkills">
                  {% for skill in minorSkill %}
                    <span class="tag tag--pill tag--sub tag--lg">
                      <small>{{skill}}</small>
                    </span>
                  {% endfor %}
                </div>
                {% endif %}

              </div>
            </div>

            <div class="devInfo">
              
              <h3 class="devInfo__title">Projects</h3>
              <div class="grid grid--two">
              {% if profile.project_set.all %}
                {% comment %} {% for project in profile.project_set.all %} {% endcomment %}
                {% for project in projects %}
                  <div class="column">
                    <div class="card project">
                      <a href="{% url 'project:About' project.id  %}" class="project">
                        {% if project.imageURL == '' %}
                        <img class="project__thumbnail" src="{% static 'media/project_default/default.jpg' %}" alt="project thumbnail" />
                        {% else %}
                        <img class="project__thumbnail" src="{{project.imageURL}}" alt="project thumbnail" />
                        {% endif %}
                        <div class="card__body">
                          <h3 class="project__title">{{project.title}}</h3>
                          <p><a class="project__author" href="profile.html">By {{project.owner.name}}</a></p>
                          <p class="project--rating">
                            <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                            Feedback ({{project.vote_count}} Vote{{project.vote_count|pluralize:"s"}})
                          </p>
                          <div class="project__tags">
                            
                            {% for tag in project.tags.all|slice:":3" %}
                            <span class="tag tag--pill tag--main">
                              <small>{{tag}}</small>
                            </span>
                            {% endfor %}

                          </div>
                        </div>
                      </a>
                    </div>
                  </div>
                {% endfor %}

                {% include 'pagination.html' with querySet=projects custom_range=custom_range %}
              {% else %}
                No Project yet
              {% endif %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

    
{% endblock body %}
{% block script %}
<script>

</script>
{% endblock script %}