Dev Search/Home/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('project/', include('project.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="user/reset_password.html"),name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='user/reset_password_sent.html'),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/reset.html'),name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="user/reset_password_complete.html"),name="password_reset_complete"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# 1 - User submits email for reset              //PasswordResetView.as_view()           //name="reset_password"
# 2 - Email sent message                        //PasswordResetDoneView.as_view()        //name="passsword_reset_done"
# 3 - Email with link and reset instructions    //PasswordResetConfirmView()            //name="password_reset_confirm"
# 4 - Password successfully reset message       //PasswordResetCompleteView.as_view()   //name="password_reset_complete"

Dev Search/api/urls.py
from django.urls import path , include
from . import views

app_name = 'api'

from rest_framework_simplejwt.views import (
    TokenObtainPairView, #generate json web token
    TokenRefreshView,#generate refresh web token
)

urlpatterns = [
    path('user/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('user/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('project/', views.getProjects),
    path('project/<str:pk>/', views.getProject),
    path('project/<str:pk>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag),
]

Dev Search/project/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'project'

urlpatterns = [
    path('', views.index , name="Home"),
    path('createproject/', views.createProject , name="Create"),
    path('updateproject/<str:pk>/', views.updateProject , name="Update"),
    path('deleteproject/<str:pk>/', views.deleteProject , name="Delete"),
    path('<str:pk>/', views.about , name="About"),
]

Dev Search/user/urls.py
from django.urls import path , include
from . import views 

app_name = 'user'

urlpatterns = [
    path('', views.index , name="Home"),
    path('login/', views.loginUser , name="login"),
    path('logout/', views.logoutUser , name="logout"),
    path('register/', views.registerUser , name="register"),
    path('account/', views.userAccount , name="account"),
    path('editProfile/', views.editProfile , name="edit-profile"),
    path('createSkill/', views.createSkill , name="create-skill"),
    path('inbox/', views.inbox , name="inbox"),
    path('viewMessage/<str:pk>/', views.viewMessage , name="viewMessage"),
    path('createMessage/<str:pk>/', views.createMessage , name="createMessage"),
    path('deleteSkill/<str:pk>/', views.deleteSkill , name="delete-skill"),
    path('updateSkill/<str:pk>/', views.updateSkill , name="update-skill"),
    path('profile/<str:pk>/', views.profile , name="Profile"),
]

Dev Search/templates/base-project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link
      rel="shortcut icon"
      href="{% static 'images/favicon.ico' %}"
      type="image/x-icon"
    />
    <!-- Icon - IconMonster -->
    <link
      rel="stylesheet"
      href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css"
    />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />

    <title>DevSearch - Connect with Developers!</title>

    <title>{% block title %}{% endblock title %}</title>

    {% block style %}{% endblock style %}
  </head>

  <body>
    <!-- Header Section -->
    <header class="header">
      <div class="container container--narrow">
        <a href="{% url 'user:Home' %}" class="header__logo">
          <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
        </a>
        <nav class="header__nav">
          <input type="checkbox" id="responsive-menu" />
          <label for="responsive-menu" class="toggle-menu">
            <span>Menu</span>
            <div class="toggle-menu__lines"></div>
          </label>
          <ul class="header__menu">
            <li class="header__menuItem">
              <a href="{% url 'user:Home' %}">Developers</a>
            </li>
            <li class="header__menuItem">
              <a href="{% url 'project:Home' %}">Projects</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="header__menuItem">
              <a href="{% url 'user:inbox' %}">Inbox</a>
            </li>
            <li class="header__menuItem">
              <a href="{% url 'user:account' %}">Profile</a>
            </li>
            <li class="header__menuItem">
              <a href="{% url 'user:logout' %}" class="btn btn--sub">Logout</a>
            </li>
            {% else %}
            <li class="header__menuItem">
              <a href="{% url 'user:login' %}" class="btn btn--sub"
                >Login/Sign Up</a
              >
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </header>

    {% block body %}{% endblock body %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" ></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js" ></script>

    {% if messages %} {% for message in messages %}
    <div class="alert alert--{{ message.tags }}">
      <p class="alert__message">{{message}}</p>
      <button class="alert__close">⨯</button>
    </div>
    {% endfor %} {% endif %}
 
    <script src="{% static 'js/pagination.js' %}"></script>
    <script src="{% static 'js/message-timeout.js' %}"></script>

    {% block script %}{% endblock script %}
  </body>
</html>

Dev Search/templates/pagination.html
{% if querySet.has_other_pages %}
<!--  Pagination start here  -->
<div class="pagination">
    <ul class="container">


        {% if querySet.has_previous %}
            <li><a href="?page={{querySet.previous_page_number}}" class="pageLink btn" data-page="{{querySet.previous_page_number}}">&#10094; Prev</a></li>
        {% endif %}
        
        {% for page in custom_range %}
            {% if page == querySet.number %}
                <li><a href="?page={{page}}" class="pageLink btn btn--sub" data-page="{{page}}">{{page}}</a></li>
            {% else %}
                <li><a href="?page={{page}}" class="pageLink btn" data-page="{{page}}">{{page}}</a></li>
            {% endif %}
        {% endfor %}

        {% if querySet.has_next %}
        <li><a href="?page={{querySet.next_page_number}}" class="pageLink btn" data-page="{{querySet.next_page_number}}">Next &#10095;</a></li>
        {% endif %}
        

    </ul>
</div>
{% endif %}